export enum PermissionCode {
  CONFIG_VER = 'CONFIGURACION_VER',
  GALPONES_CREAR = 'GALPONES_CREAR',
  GALPONES_VER = 'GALPONES_VER',
  GALPONES_EDITAR = 'GALPONES_EDITAR',
  GALPONES_ELIMINAR = 'GALPONES_ELIMINAR',
  RAZAS_CREAR = 'RAZAS_CREAR',
  RAZAS_VER = 'RAZAS_VER',
  RAZAS_EDITAR = 'RAZAS_EDITAR',
  RAZAS_ELIMINAR = 'RAZAS_ELIMINAR',
  USUARIOS_CREAR = 'USUARIOS_CREAR',
  USUARIOS_VER = 'USUARIOS_VER',
  USUARIOS_EDITAR = 'USUARIOS_EDITAR',
  USUARIOS_DESACTIVAR = 'USUARIOS_DESACTIVAR',
  USUARIOS_ELIMINAR = 'USUARIOS_ELIMINAR',
  HUEVOS_CREAR = 'HUEVOS_CREAR',
  HUEVOS_VER = 'HUEVOS_VER',
  HUEVOS_EDITAR = 'HUEVOS_EDITAR',
  UNIDADES_MEDIDA_CREAR = 'UNIDADES_MEDIDA_CREAR',
  UNIDADES_MEDIDA_VER = 'UNIDADES_MEDIDA_VER',
  UNIDADES_MEDIDA_EDITAR = 'UNIDADES_MEDIDA_EDITAR',
  UNIDADES_MEDIDA_ELIMINAR = 'UNIDADES_MEDIDA_ELIMINAR',
  INSUMOS_CREAR = 'INSUMOS_CREAR',
  INSUMOS_VER = 'INSUMOS_VER',
  INSUMOS_EDITAR = 'INSUMOS_EDITAR',
  INSUMOS_ELIMINAR = 'INSUMOS_ELIMINAR',
  LOTES_CREAR = 'LOTES_CREAR',
  LOTES_VER = 'LOTES_VER',
  LOTES_EDITAR = 'LOTES_EDITAR',
  LOTES_ELIMINAR = 'LOTES_ELIMINAR',
  PERMISOS_CREAR = 'PERMISOS_CREAR',
  PERMISOS_VER = 'PERMISOS_VER',
  PERMISOS_EDITAR = 'PERMISOS_EDITAR',
  PERMISOS_ELIMINAR = 'PERMISOS_ELIMINAR',
  CATEGORIAS_CREAR = 'CATEGORIAS_CREAR',
  CATEGORIAS_VER = 'CATEGORIAS_VER',
  CATEGORIAS_EDITAR = 'CATEGORIAS_EDITAR',
  CATEGORIAS_ELIMINAR = 'CATEGORIAS_ELIMINAR',
  ROLES_CREAR = 'ROLES_CREAR',
  ROLES_VER = 'ROLES_VER',
  ROLES_EDITAR = 'ROLES_EDITAR',
  ROLES_ELIMINAR = 'ROLES_ELIMINAR',
  REPORTES_VER = 'REPORTES_VER',
  REPORTES_CREAR = 'REPORTES_CREAR',
  BACKUP_GESTIONAR = 'BACKUP_GESTIONAR',
}

export const PERMISSIONS_CATALOG = [
  { codigo: 1, nombre: PermissionCode.CONFIG_VER, descripcion: 'Ver configuración general' },
  { codigo: 10, nombre: PermissionCode.GALPONES_CREAR, descripcion: 'Crear galpones' },
  { codigo: 11, nombre: PermissionCode.GALPONES_VER, descripcion: 'Ver galpones' },
  { codigo: 12, nombre: PermissionCode.GALPONES_EDITAR, descripcion: 'Editar galpones' },
  { codigo: 13, nombre: PermissionCode.GALPONES_ELIMINAR, descripcion: 'Eliminar galpones' },
  { codigo: 20, nombre: PermissionCode.RAZAS_CREAR, descripcion: 'Crear razas' },
  { codigo: 21, nombre: PermissionCode.RAZAS_VER, descripcion: 'Ver razas' },
  { codigo: 22, nombre: PermissionCode.RAZAS_EDITAR, descripcion: 'Editar razas' },
  { codigo: 23, nombre: PermissionCode.RAZAS_ELIMINAR, descripcion: 'Eliminar razas' },
  { codigo: 30, nombre: PermissionCode.USUARIOS_CREAR, descripcion: 'Crear usuarios' },
  { codigo: 31, nombre: PermissionCode.USUARIOS_VER, descripcion: 'Ver usuarios' },
  { codigo: 32, nombre: PermissionCode.USUARIOS_EDITAR, descripcion: 'Editar usuarios' },
  { codigo: 33, nombre: PermissionCode.USUARIOS_DESACTIVAR, descripcion: 'Desactivar usuarios' },
  { codigo: 34, nombre: PermissionCode.USUARIOS_ELIMINAR, descripcion: 'Eliminar usuarios' },
  { codigo: 40, nombre: PermissionCode.HUEVOS_CREAR, descripcion: 'Crear registros de huevos' },
  { codigo: 41, nombre: PermissionCode.HUEVOS_VER, descripcion: 'Ver inventario de huevos' },
  { codigo: 42, nombre: PermissionCode.HUEVOS_EDITAR, descripcion: 'Editar registros de huevos' },
  { codigo: 50, nombre: PermissionCode.UNIDADES_MEDIDA_CREAR, descripcion: 'Crear unidades de medida' },
  { codigo: 51, nombre: PermissionCode.UNIDADES_MEDIDA_VER, descripcion: 'Ver unidades de medida' },
  { codigo: 52, nombre: PermissionCode.UNIDADES_MEDIDA_EDITAR, descripcion: 'Editar unidades de medida' },
  { codigo: 53, nombre: PermissionCode.UNIDADES_MEDIDA_ELIMINAR, descripcion: 'Eliminar unidades de medida' },
  { codigo: 60, nombre: PermissionCode.INSUMOS_CREAR, descripcion: 'Crear insumos' },
  { codigo: 61, nombre: PermissionCode.INSUMOS_VER, descripcion: 'Ver insumos' },
  { codigo: 62, nombre: PermissionCode.INSUMOS_EDITAR, descripcion: 'Editar insumos' },
  { codigo: 63, nombre: PermissionCode.INSUMOS_ELIMINAR, descripcion: 'Eliminar insumos' },
  { codigo: 70, nombre: PermissionCode.LOTES_CREAR, descripcion: 'Crear lotes' },
  { codigo: 71, nombre: PermissionCode.LOTES_VER, descripcion: 'Ver lotes' },
  { codigo: 72, nombre: PermissionCode.LOTES_EDITAR, descripcion: 'Editar lotes' },
  { codigo: 73, nombre: PermissionCode.LOTES_ELIMINAR, descripcion: 'Eliminar lotes' },
  { codigo: 80, nombre: PermissionCode.PERMISOS_CREAR, descripcion: 'Crear permisos' },
  { codigo: 81, nombre: PermissionCode.PERMISOS_VER, descripcion: 'Ver permisos' },
  { codigo: 82, nombre: PermissionCode.PERMISOS_EDITAR, descripcion: 'Editar permisos' },
  { codigo: 83, nombre: PermissionCode.PERMISOS_ELIMINAR, descripcion: 'Eliminar permisos' },
  { codigo: 90, nombre: PermissionCode.CATEGORIAS_CREAR, descripcion: 'Crear categorías' },
  { codigo: 91, nombre: PermissionCode.CATEGORIAS_VER, descripcion: 'Ver categorías' },
  { codigo: 92, nombre: PermissionCode.CATEGORIAS_EDITAR, descripcion: 'Editar categorías' },
  { codigo: 93, nombre: PermissionCode.CATEGORIAS_ELIMINAR, descripcion: 'Eliminar categorías' },
  { codigo: 100, nombre: PermissionCode.ROLES_CREAR, descripcion: 'Crear roles' },
  { codigo: 101, nombre: PermissionCode.ROLES_VER, descripcion: 'Ver roles' },
  { codigo: 102, nombre: PermissionCode.ROLES_EDITAR, descripcion: 'Editar roles' },
  { codigo: 103, nombre: PermissionCode.ROLES_ELIMINAR, descripcion: 'Eliminar roles' },
  { codigo: 110, nombre: PermissionCode.REPORTES_VER, descripcion: 'Ver reportes' },
  { codigo: 111, nombre: PermissionCode.REPORTES_CREAR, descripcion: 'Crear reportes' },
  { codigo: 120, nombre: PermissionCode.BACKUP_GESTIONAR, descripcion: 'Gestionar backups' },
];

export const PERMISSION_NAMES = PERMISSIONS_CATALOG.map((permission) => permission.nombre);
